// <auto-generated />
using System;
using DomainDrivenDesignExample.API.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomainDrivenDesignExample.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310193953_check")]
    partial class check
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.Cinema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas", "catalogs");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.CinemaHall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOperational")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SupportedTechnologies")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("CinemaHalls", "catalogs");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EarliestShowingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrentlyShowing")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PosterImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShowingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShowingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupportedTechnology")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Movies", "catalogs");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CinemaHallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaHallId");

                    b.ToTable("Seats", "catalogs");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Scheduling.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Schedules", "scheduling");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Ticketing.Aggregate.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength();

                    b.Property<Guid>("TicketIssuanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketIssuanceId");

                    b.ToTable("Tickets", "Ticketing");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Ticketing.Aggregate.TicketIssuance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDiscountApplied")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScheduledMovieShowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ScreeningDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TicketIssuance", "Ticketing");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Ticketing.SeatHoldAggregate.SeatHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ScheduledMovieShowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ScreeningDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SeatHolds", "Ticketing");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.Cinema", b =>
                {
                    b.OwnsOne("DomainDrivenDesignExample.API.BoundedContexts.Catalog.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CinemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Country");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("AddressDescription");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("District");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Street");

                            b1.HasKey("CinemaId");

                            b1.ToTable("Cinemas", "catalogs");

                            b1.WithOwner()
                                .HasForeignKey("CinemaId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.CinemaHall", b =>
                {
                    b.HasOne("DomainDrivenDesignExample.API.BoundedContexts.Catalog.Cinema", "Cinema")
                        .WithMany("Halls")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.Movie", b =>
                {
                    b.OwnsOne("DomainDrivenDesignExample.API.BoundexContexts.ValueObjects.Duration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Minutes")
                                .HasColumnType("float")
                                .HasColumnName("DurationMinutes");

                            b1.HasKey("MovieId");

                            b1.ToTable("Movies", "catalogs");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.Seat", b =>
                {
                    b.HasOne("DomainDrivenDesignExample.API.BoundedContexts.Catalog.CinemaHall", "CinemaHall")
                        .WithMany("Seats")
                        .HasForeignKey("CinemaHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DomainDrivenDesignExample.API.SharedKernels.ValueObjects.SeatPosition", "SeatPosition", b1 =>
                        {
                            b1.Property<Guid>("SeatId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Number")
                                .HasColumnType("int")
                                .HasColumnName("Number");

                            b1.Property<string>("Row")
                                .IsRequired()
                                .HasMaxLength(1)
                                .IsUnicode(false)
                                .HasColumnType("char(1)")
                                .HasColumnName("Row")
                                .IsFixedLength();

                            b1.HasKey("SeatId");

                            b1.ToTable("Seats", "catalogs");

                            b1.WithOwner()
                                .HasForeignKey("SeatId");
                        });

                    b.Navigation("CinemaHall");

                    b.Navigation("SeatPosition")
                        .IsRequired();
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Scheduling.Schedule", b =>
                {
                    b.OwnsOne("DomainDrivenDesignExample.API.SharedKernels.ValueObjects.Price", "TicketPrice", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("Currency");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.OwnsOne("DomainDrivenDesignExample.API.SharedKernels.ValueObjects.ShowTime", "ShowTime", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time")
                                .HasColumnName("ShowTime_EndTime");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time")
                                .HasColumnName("ShowTime_StartTime");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("ShowTime")
                        .IsRequired();

                    b.Navigation("TicketPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Ticketing.Aggregate.Ticket", b =>
                {
                    b.HasOne("DomainDrivenDesignExample.API.BoundedContexts.Ticketing.Aggregate.TicketIssuance", "TicketIssuance")
                        .WithMany("TicketList")
                        .HasForeignKey("TicketIssuanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DomainDrivenDesignExample.API.SharedKernels.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("TicketId");

                            b1.ToTable("Tickets", "Ticketing");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsOne("DomainDrivenDesignExample.API.SharedKernels.ValueObjects.SeatPosition", "SeatPosition", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Number")
                                .HasColumnType("int")
                                .HasColumnName("Number");

                            b1.Property<string>("Row")
                                .IsRequired()
                                .HasMaxLength(1)
                                .IsUnicode(false)
                                .HasColumnType("char(1)")
                                .HasColumnName("Row")
                                .IsFixedLength();

                            b1.HasKey("TicketId");

                            b1.ToTable("Tickets", "Ticketing");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("SeatPosition")
                        .IsRequired();

                    b.Navigation("TicketIssuance");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Ticketing.SeatHoldAggregate.SeatHold", b =>
                {
                    b.OwnsOne("DomainDrivenDesignExample.API.SharedKernels.ValueObjects.SeatPosition", "SeatPosition", b1 =>
                        {
                            b1.Property<Guid>("SeatHoldId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Number")
                                .HasColumnType("int")
                                .HasColumnName("Number");

                            b1.Property<string>("Row")
                                .IsRequired()
                                .HasMaxLength(1)
                                .IsUnicode(false)
                                .HasColumnType("char(1)")
                                .HasColumnName("Row")
                                .IsFixedLength();

                            b1.HasKey("SeatHoldId");

                            b1.ToTable("SeatHolds", "Ticketing");

                            b1.WithOwner()
                                .HasForeignKey("SeatHoldId");
                        });

                    b.Navigation("SeatPosition")
                        .IsRequired();
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.Cinema", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Catalog.CinemaHall", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("DomainDrivenDesignExample.API.BoundedContexts.Ticketing.Aggregate.TicketIssuance", b =>
                {
                    b.Navigation("TicketList");
                });
#pragma warning restore 612, 618
        }
    }
}
